### ISSUE TITLE
Make it possible for admins(maybe users) to view and edit the code

### ISSUE THREAD

**Issue by CamoBrie** [Luca-Castelnuovo/TestingPlatform#13]
title

**Comment by Luca-Castelnuovo** [comment]
goeie functie als betasterren af is gaan we het zeker doen

**Comment by CamoBrie** [comment]
Yo, ik ga wss morgemiddag werken aan betasterren
oja, ik kan niet meer inloggen

**Comment by Luca-Castelnuovo** [comment]
? verkeerde wachtwoord

**Comment by CamoBrie** [comment]
zou kunnen

**Comment by Luca-Castelnuovo** [comment]
werkt de pasword reset

**Comment by CamoBrie** [comment]
ja

**Comment by CamoBrie** [comment]
denk het wel

**Comment by CamoBrie** [comment]
nvm, ik heb het vermeerkde email adres

**Comment by Luca-Castelnuovo** [comment]
lel

**Comment by CamoBrie** [comment]
nvm de nvm

**Comment by CamoBrie** [comment]
hij doet t nog steeds niet

**Comment by CamoBrie** [comment]
xD

**Comment by Luca-Castelnuovo** [comment]
uhm wat werkt nier

**Comment by CamoBrie** [comment]
idk

**Comment by CamoBrie** [comment]
ik zie later wel

**Comment by Luca-Castelnuovo** [comment]
krijg je geen email?

**Comment by CamoBrie** [comment]
mn lever werkt niet

**Comment by CamoBrie** [comment]
ne

**Comment by Luca-Castelnuovo** [comment]
mn lever werkt niet ????????

**Comment by CamoBrie** [comment]
ja, jou nier werkt niet

**Comment by CamoBrie** [comment]
xD

**Comment by CamoBrie** [comment]
uhm wat werkt nier
--

**Comment by CamoBrie** [comment]
`<script>var a=0,b=1,c=30;function d(){a+=b;document.getElementById("e").innerHTML=a;}function f(){if(a>=c){a-=c;c*=1.95;b*=2;document.getElementById("e").innerHTML=a;document.getElementById("c").innerHTML=c;}}</script><button onclick="d()">c</button><span id="e"></span><button onclick="f()"><span id="c">30</span></button>


`

**Comment by Luca-Castelnuovo** [comment]
hoezo werk mijn nier niet

**Comment by CamoBrie** [comment]
dat zei je

**Comment by CamoBrie** [comment]
Luca-Castelnuovo commented a minute ago: uhm wat werkt nier

**Comment by Luca-Castelnuovo** [comment]
ah

**Comment by CamoBrie** [comment]
xD

**Comment by Luca-Castelnuovo** [comment]
wat is de js code

**Comment by CamoBrie** [comment]
korte clickergame in the world

**Comment by CamoBrie** [comment]
maar 383 characters

**Comment by CamoBrie** [comment]
dus goed genoeg voor een tweet

**Comment by Luca-Castelnuovo** [comment]
ok maar moet er geen html bij

**Comment by CamoBrie** [comment]
<script>var a=0,b=1,c=30;function d(){a+=b;document.getElementById("e").innerHTML=a;}function f(){if(a>=c){a-=c;c*=1.95;b*=2;document.getElementById("e").innerHTML=a;document.getElementById("c").innerHTML=c;}}</script><button onclick="d()">c</button><span id="e"></span><button onclick="f()"><span id="c">30</span></button>

**Comment by CamoBrie** [comment]
he

**Comment by CamoBrie** [comment]
hij verkort het

**Comment by CamoBrie** [comment]
het wekt nog steeds niet

**Comment by CamoBrie** [comment]
![image](https://user-images.githubusercontent.com/18614361/43802212-6735def6-9a95-11e8-8226-7017c6cb7e44.png)

**Comment by Luca-Castelnuovo** [comment]
upload het bestand

**Comment by CamoBrie** [comment]
oja

**Comment by CamoBrie** [comment]
kan geen html uploaden

**Comment by CamoBrie** [comment]
nvm dan

**Comment by Luca-Castelnuovo** [comment]
upload het als .txt

**Comment by CamoBrie** [comment]
ne

**Comment by CamoBrie** [comment]
ik laat het later wel n keer zien 🗡

**Comment by Luca-Castelnuovo** [comment]
misschien een share edit link optie

**Comment by Luca-Castelnuovo** [comment]
maar gaat nu niet gebeuren dit project heeft geen prioriteit
